[package]
authors = ["Dominic <email@domi-me.de>"]
edition = "2018"
name = "deep-api"
version = "0.1.0"
[dependencies]
actix = "0.8.3"
actix-web = "1.0.8"
base64 = "0.11.0"
env_logger = "0.7.1"
err-derive = "0.2.1"
failure = "0.1.6"
log = "0.4.8"
serde = "1.0.102"
serde_json = "1.0.41"
tempfile = "3.1.0"
toml = "0.5.5"
regex = "1.3.1"
structopt = "0.3.4"
derive_more = "0.99.2"
actix-cors = "0.1.0"
[dependencies.uuid]
features = ["serde", "v4"]
version = "0.8.1"
