FROM rust:1.40 as builder
USER root
ENV USER=root
RUN mkdir workspace && \
    cd workspace && \
    cargo new api --lib && \
    cargo new grpc-api --lib && \
    cargo new testing --lib
WORKDIR /workspace

RUN rustup component add rustfmt

COPY Cargo.toml .
COPY grpc-api/Cargo.toml grpc-api
COPY grpc-api/proto grpc-api/proto
COPY grpc-api/build.rs grpc-api
COPY testing/Cargo.lock testing
COPY testing/Cargo.toml testing
RUN cd testing && cargo build --release
COPY . .


RUN cd testing && cargo build --release

COPY . .

RUN cd testing && cargo build --release

FROM rust:1.40

RUN apt-get update &&\
    apt-get install -y \
    less \
    locales \
    ca-certificates \
    libicu63 \
    libssl1.1 \
    libc6 \
    libgcc1 \
    libgssapi-krb5-2 \
    liblttng-ust0 \
    libstdc++6 \
    zlib1g \
    curl &&\
    curl -L https://github.com/PowerShell/PowerShell/releases/download/v7.0.0-preview.4/powershell-7.0.0-preview.4-linux-x64.tar.gz -o /tmp/powershell.tar.gz &&\
    mkdir -p /opt/microsoft/powershell/7-preview &&\
    tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7-preview &&\
    chmod +x /opt/microsoft/powershell/7-preview/pwsh &&\
    ln -s /opt/microsoft/powershell/7-preview/pwsh /usr/bin/pwsh &&\
    apt-get install -y --no-install-recommends wine python3 && \
    ln -s /media/examples/ examples

COPY --from=builder /workspace/target/release/testing .
EXPOSE 50051

CMD ["./testing","--config", "examples/assignments.toml"]
