FROM rust:1.40 as builder
RUN USER=root cargo new api --lib
WORKDIR /api

COPY . .

RUN rustup component add rustfmt && cd api && cargo build --release

FROM rust:1.40

COPY --from=builder /api/target/release/api .
EXPOSE 8080

CMD ["./api"]
