version: "3"
services:
  api:
    image: dominicwrege/depp-project-api
    ports:
      - 6000:6000
    env_file:
      - ./example.env
    links:
      - "db:database"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./example.env
    volumes:
      - ../db-data:/var/lib/postgresql/data
  web:
    image: dominicwrege/depp-project-web:latest
    ports:
      - 5000:5000
    env_file:
      - ./example.env
    depends_on:
      - db
    links:
      - "db:database"