FROM rust:1.40 as builder
USER root
ENV USER=root
RUN mkdir workspace && \
    cd workspace && \
    cargo new api --lib && \
    cargo new grpc-api --lib && \
    cargo new testing --lib
WORKDIR /workspace

RUN rustup component add rustfmt

COPY Cargo.toml .
COPY grpc-api/Cargo.toml grpc-api
COPY grpc-api/proto grpc-api/proto
COPY grpc-api/build.rs grpc-api
COPY api/Cargo.lock api
#COPY api/Cargo.toml api
RUN cd api && cargo build --release
COPY . .

RUN cd api && cargo build --release

FROM rust:1.40

COPY --from=builder /workspace/target/release/api .
EXPOSE 8080

CMD ["./api"]