FROM rust:1.41 as builder
USER root
ENV USER=root
RUN apt update && \
    apt install musl musl-dev musl-tools
WORKDIR /workspace

RUN rustup component add rustfmt && rustup target add x86_64-unknown-linux-musl

COPY . .

RUN cd api && cargo build --release --target x86_64-unknown-linux-musl

FROM alpine:latest

COPY --from=builder /workspace/target/x86_64-unknown-linux-musl/release/api .
EXPOSE 8080

CMD ["./api"]