version: "3"
services:
  testing:
    image: dominicwrege/depp-testing
    ports:
      - 50051:50051
    volumes:
      - ./testing/examples:/media/examples
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/scripts:/tmp/scripts
  api:
    image: dominicwrege/depp-project-api
    ports:
      - 8080:8080
    environment:
      - RPC_URL=http://testing:50051
  testing-ubuntu:
    image: dominicwrege/depp-project-ubuntu:latest
  docs:
    build: docs
    ports:
      - 4001:80
    volumes:
      - ./docs:/usr/share/nginx/html/
  swagger_ui:
    depends_on:
      - docs
    image: swaggerapi/swagger-ui
    environment:
      - API_URL=http://127.0.0.1:4001/api.openapi.yml
    ports:
      - 4000:8080
