### Send POST request with json body
POST http://127.0.0.1:8080/submission
Content-Type: application/json

{
  "iliasId": 1984,
  "sourceCode": "JGlucHV0ID0gJGFyZ3NbMF0KCiRyYXcgPSBnZXQtY29udGVudCAkaW5wdXQgLVJhdwokcmVnZXg9Iig/PCFbMC05XC1dKVswXSooKDEwMDAwKXwoWzAtOV17MCwzfVsxLTldKXwoWzAtOV17MCwyfVsxLTldWzAtOV0/KXwoWzAtOV0/WzEtOV1bMC05XXswLDJ9KXwoWzEtOV1bMC05XXswLDN9KSkoW1wuXCxdWzAtOV0qKT8oW1xzXG5ccl0rfFthLXpBLVpdKVthLXpBLVpdKiIKKCRyYXcgfCBTZWxlY3QtU3RyaW5nIC1BbGxNYXRjaGVzIC1QYXR0ZXJuICRyZWdleCkuTWF0Y2hlcyB8IEZvckVhY2gtT2JqZWN0ewoJJGN1cnJlbnQ9JF8uVmFsdWUKCSRjdXJyZW50IC1yZXBsYWNlICJccyIsJyAnCn0K",
  "assigmentId": 4
}

### Get
GET http://127.0.0.1:8080/result/1984

###
