[package]
name = "grpc-api"
version = "0.1.0"
authors = ["DomincWrege <dominic.wrege001@stud.fh-dortmund.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.1.0-beta.1"
bytes = "0.4"
prost = "0.5"
serde = { version = "1.0", features = ["derive"] }
envy = "0.4.1"

[build-dependencies]
tonic-build = "0.1.0-beta.1"
