## TODO save in postrgesql
name = "Prof. Recker"

# takes writes 'HalloWorld' into hallo.txt
[assignments.f74f179b-6f8e-4d7d-9dae-299c4e3581de]
name = "Task 1 Hello World"
type = "Shell"
solution = '''#!/bin/bash
echo "Hello World"
mkdir dir22
echo "some thing differnt ..." >> "dir22/lorme.txt"
'''
## takes 1 argument, reverse and print it out
[assignments."53dc1a88-2be1-40c5-8bbe-fe7efb04b03f"]
name = "Task 2 Bash reverse"
type = "Bash"
args = ["rackrent"]
solution = '''#! /bin/bash
input=$1
length=${#input}
reverse=""
for i in $(seq 1 $length )
do
	reverse+=${input:$length-i:1}
done
echo "Ausgabe umgekehrt: $reverse"
'''

# calc fib by given number
[assignments.d836564e-1837-48c9-91d0-edf0c7f998e7]
name = "Task 3 Python3 fib"
type = "Python3"
solution  = '''import sys
def fib2(n):
    if n == 0 or n == 1:
        return 1
    return n * fib2(n-1)

n1 = int(sys.argv[1])
n2 = int(sys.argv[2])
print("fib:", fib2(n1), fib2(n2))
'''
args = ["5", "7"]

# from pk7
[assignments.667caf1f-91cd-48cd-93db-2d4c8410f594]
name = "Pk7 Aufgabe 1 awk akademisches_jahrbuch"
type = "Bash"
solution  = '''
#!/bin/bash
grep -e 'Oktober, 2017' akademisches_jahrbuch.txt | grep -o -e '^\w\+[,][ ]\w\+'
grep -e 'Wilhelm Schwick' akademisches_jahrbuch.txt | awk 'BEGIN {FS=" - "} { print $2 }'
'''
include-files = ["examples/akademisches_jahrbuch.txt"]
# # # create some directories and files
# [assignments.c29e0436-9c6f-466e-8e9d-6968416c846c]
# name = "Task 4 crate directories"
# type = "Batch"
# solution  = "examples/task4_directories.bat"

# # # parse file
# [assignments.77ca13fe-dcda-4ec6-959c-fec31f181380]
# name = "Task 5 Powershell parse file with regex"
# type = "PowerShell"
# solution  = "examples/task5_regex.ps1"
# include-files = ["examples/task5-input.txt"]
