name = "Blatt 42"

# takes writes 'HalloWorld' into hallo.txt
[[assignment]]
name = "Task 1 Hello World"
type = "Shell"
solution-path = "examples/task1_helloworld.bat"

## takes 1 argument, reverse and print it out
[[assignment]]
name = "Task 2 Bash reverse"
type = "Bash"
solution-path = "examples/task2_reverse.sh"
args = ["rackrent"]

# calc fib by given number
[[assignment]]
name = "Task 3 Python3 fib"
type = "Python3"
solution-path  = "examples/task3_fib.py"
args = ["5", "7"]


[[assignment]]
name = "Pk7 Aufgabe 1 awk akademisches_jahrbuch"
type = "Bash"
include-files = ["examples/akademisches_jahrbuch.txt"]
solution-path  = "examples/pk7-Aufgabe1.sh"

# create some directories and files
#[[assignment]]
#name = "Task 4 crate directories"
#type = "Batch"
#solution-path  = "some batch"

#
[[assignment]]
name = "Task 5 Powershell parse file with regex"
type = "PowerShell"
solution-path  = "examples/task5_regex.ps1"
include-files = ["examples/task5-input.txt"]
