FROM rust:1.44 as builder
USER root
ENV USER=root
RUN rustup target add x86_64-unknown-linux-musl && \
    apt update && \
    apt install -y musl musl-dev musl-tools
WORKDIR /workspace

RUN rustup component add rustfmt && rustup target add x86_64-unknown-linux-musl

COPY . .

RUN cd testing && cargo build --release --target x86_64-unknown-linux-musl

FROM alpine:latest

COPY --from=builder /workspace/target/x86_64-unknown-linux-musl/release/testing .
EXPOSE 50051

CMD ["./testing"]
