FROM rust:1.42 as builder
USER root
ENV USER=root
RUN apt update && \
    apt install musl musl-dev musl-tools
WORKDIR /workspace

RUN rustup component add rustfmt && rustup target add x86_64-unknown-linux-musl

COPY . .

RUN cd db-edit && cargo build --release --target x86_64-unknown-linux-musl

FROM alpine:latest

COPY --from=builder /workspace/target/x86_64-unknown-linux-musl/release/db-edit .
COPY ./db-edit/static ./static
COPY ./db-edit/templates ./templates

EXPOSE 5000

CMD ["./db-edit"]
