FROM rust:1.44 as builder
USER root
ENV USER=root
RUN apt update && \
    apt install -y musl musl-dev musl-tools
WORKDIR /workspace

RUN rustup component add rustfmt && rustup target add x86_64-unknown-linux-musl

COPY . .

RUN cd assign-mngr && cargo build --target x86_64-unknown-linux-musl

FROM alpine:latest 

COPY --from=builder /workspace/target/x86_64-unknown-linux-musl/debug/assign-mngr .
COPY ./assign-mngr/static ./static
COPY ./assign-mngr/templates ./templates
COPY ./assign-mngr/package.json .
COPY ./assign-mngr/yarn.lock .

RUN apk add yarn &&\
    yarn install --modules-folder ./static/node_modules

EXPOSE 5000

CMD ["./assign-mngr"]
