name: build Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: build images
        env:
          DOCKER_HUB: ${{ secrets.DOCKER_HUB }}
          DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
        run: |
         echo "login docker"
         docker login -u $DOCKER_HUB -p  DOCKER_HUB_KEY
         echo "building api"
         docker build . -t api -f ./Docker-Files/Dockerfile-API --tag dominicwrege/depp-project-api:latest
         docker push dominicwrege/depp-project-api:latest 
         echo "building web"
         docker build . -t web -f Docker-Files/Dockerfile-Assign-mngr --tag dominicwrege/depp-project-web:latest
         docker push dominicwrege/depp-project-web:latest
         echo "building testing"
         docker build . -t testing -f Docker-Files/Dockerfile-Testing --tag dominicwrege/depp-testing:latest
         docker push dominicwrege/depp-testing:latest
         echo "done"
