name: build Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: build api
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_KEY }}
          repository: dominicwrege/depp-project-api
          tags: latest
          dockerfile: {path}/Docker-Files/Dockerfile-API   
      - name: build web
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_KEY }}
          repository: dominicwrege/depp-project-web
          tags: latest
          dockerfile: {path}/Docker-Files/Dockerfile-Assign-mngr
      - name: build testing
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_KEY }}
          repository: dominicwrege/dominicwrege/depp-testing
          tags: latest
          dockerfile: {path}/Docker-Files/Dockerfile-Testing